### ISSUE TITLE
Still not working after the update

### ISSUE THREAD

**Issue by phantasmaz** [JustOptimize/return-ShowHiddenChannels#18]
Just downloaded the updated version of the plugin, and it is still not working. Any solutions?

**Comment by JustOptimize** [comment]
It isn't supposed to be working, I'm working on it

**Comment by Banquo88** [comment]
not trying to rush, just curious if we have a ballpark eta

**Comment by JustOptimize** [comment]
Not having much free time having homework and exams, if anyone wants to help me please do.
The problem is that Betterdiscord is still adapting to this update so many functions are missing and at the moment I don't even know the new names of the missing "WebModules" like "ChannelItem" or "VoiceUsers".

**Comment by HistoricTheater** [comment]
All BD is doing is updating their patreon users so badges show up in your discord that you dont ask for.
Better to plan getting it out of their hands. None of the other forks are showing any activity either
