### ISSUE TITLE
(Bug) Hidden channels plugin causes servers to be marked as not read even though all channels are marked as read

### ISSUE THREAD

**Issue by Adamillo** [JustOptimize/return-ShowHiddenChannels#47]
The workaround for this bug is by muting the hidden channels, but that's not very ideal

**Comment by JustOptimize** [comment]
It's a known bug.
I already plan to fix it (see readme)

**Comment by Serega007RU** [comment]
Please take this issue as a priority, it is impossible to use discord when you have phantom notifications. Adding functions and settings to this plugin does not look so useful compared to fixing this problem

**Comment by JustOptimize** [comment]
> Please take this issue as a priority, it is impossible to use discord when you have phantom notifications. Adding functions and settings to this plugin does not look so useful compared to fixing this problem

It's a slow and painful process, I've been working on it for weeks but the only problem is that it's probably just wasted time not actually knowing what I'm doing

**Comment by GoldenChrysus** [comment]
It looks like there might be two stores that control unread statuses: one for the guild (server) and one for each channel.

The line `const UnreadStore = WebpackModules.getByProps("isForumPostUnread");` seems to return the store controlling each channels unread state (e.g. if you just set the `hasUnread` patch to always return `true`, all your channels will light up as unread, but the servers _won't_ necessarily be marked unread.

If I do `const SomeStore = WebpackModules.getByProps("hasUnread");` I get a different store than the one above, and this one seems to control server unread statuses (e.g. add a patch for `hasUnread` that returns `true` and all your servers will be marked as unread).

I'm unsure if there's some mechanism (e.g. other module) that coordinates/controls both of these states, but otherwise these stores might need to be used in tandem to determine if the server as a whole is unread based on the presence of _non-hidden_ unread channels.

**Comment by JustOptimize** [comment]
Yeah i had found the isForum.. and tried to patch it but the channel notifications were still showing so I moved on.
Will check again tomorrow

**Comment by JustOptimize** [comment]
In the latest version i added this setting
![image](https://user-images.githubusercontent.com/54294419/198371686-e83f7428-503f-4603-bcdf-d8bc6ee084e9.png)
so you people can mark as read manually

I will still work on a fix, don't worry guys

**Comment by Serega007RU** [comment]
I have enabled this option and still the hidden channel is marked as unread
![image](https://user-images.githubusercontent.com/64780091/198901896-3d3f6fc0-02d2-4c0b-a796-9f63bf6ababc.png)

**Comment by JustOptimize** [comment]
This was fixed with v0.0.7
