### ISSUE TITLE
(BUG) Last message sent in hidden channels doesn't get updated unless you restart discord

### ISSUE THREAD

**Issue by Pabsb** [JustOptimize/return-ShowHiddenChannels#81]
As title says in Hidden channels the last message sent doesn't get updated unless you restart discord.

**Comment by JustOptimize** [comment]
This is a "problem" within discord itself (probably due to optimization).
When the client receives a channel, the date is not updated because it rightly should not be used.
You could probably implement something to deflect to the problem but it would cause lag and other problems such as rate limiting

**Comment by JustOptimize** [comment]
Maybe a manual refresh button could be implemented but at this point just reload discord.
